### ISSUE TITLE
MISSING NODE - The PixtralModelLoader is Missing!

### ISSUE THREAD

**Issue by Iory1998** [SeanScripts/ComfyUI-PixtralLlamaVision#1]
Hey,

I can't find the PixtralModelLoader node. I tried to fix the install using the Manager, uninstalled the custom node and reinstalled it without success.
![image](https://github.com/user-attachments/assets/027ed044-f201-4533-a606-7a648cad8946)

**Comment by SeanScripts** [comment]
Hmm, I tried uninstalling and reinstalling via the node manager to see if there was an issue with the version that is on the registry, but it still works for me. Can you try reinstalling the latest version of transformers? Run this command in the ComfyUI_windows_portable folder (the one that has run_nvidia_gpu.bat, assuming you're on Windows):
`python_embeded\python.exe -m pip install git+https://github.com/huggingface/transformers`

**Comment by Iory1998** [comment]
Thank you. I reinstalled the custom node and its requirements and now it works properly.
Thank for you hard work. Much appreciated.

On a different note, could you please clarify this sentence?

> Requires transformers 4.45.0 for Pixtral and 4.46.0 for Llama Vision.

Do you mean we should install both versions? Is that even possible? And, I could not find Transformers 4.46.0 anywhere. Could you please provide the link for it?

**Comment by SeanScripts** [comment]
I installed Stability Matrix (which looks very convenient) and noticed I had an error loading the node if the "pixtral" or "llama-vision" folder inside the models directory was missing. I should have the folder add automatically if it's not already there. Glad it's working for you now though!

I also need to update that note. The background there is that transformers 4.45.0.dev0 added Pixtral and 4.46.0.dev0 added Llama vision, but the official release yesterday for 4.45.0 included both. If you can load the node, you should be good, but let me know if you have any issues with loading the model.

**Comment by Iory1998** [comment]
> I installed Stability Matrix (which looks very convenient) and noticed I had an error loading the node if the "pixtral" or "llama-vision" folder inside the models directory was missing. I should have the folder add automatically if it's not already there. Glad it's working for you now though!
> 
> I also need to update that note. The background there is that transformers 4.45.0.dev0 added Pixtral and 4.46.0.dev0 added Llama vision, but the official release yesterday for 4.45.0 included both. If you can load the node, you should be good, but let me know if you have any issues with loading the model.

You are absolutely correct regarding the folder creation. Please, update the node so the models are automatically created inside the LLM folder. This folder is actually used by other nodes, so it's convenient to have everything in one folder. I hardlink all the folders, but other users might not know how to. I think that what did it for me since I manually created them. 
I haven't tested the node yet since I am downloading your models. I downloaded a different version from unsloth yesterday but t didn't work
https://huggingface.co/unsloth/Llama-3.2-11B-Vision-bnb-4bit

**Comment by SeanScripts** [comment]
I'm able to load that unsloth 4bit model, but the results I'm getting with it seem pretty bad, mostly highly repetitive responses. I think it's just because this is the base model, though. You'd want to use the instruction tuned one.

Technically these are VLMs with a vision encoder as well as an LLM part, but I do think it would make sense to keep them in the same folder. I'm also thinking it might make sense to merge the two model loader nodes, since they're nearly identical and could automatically determine the model type. This would also make it compatible with other model types, in theory, as long as they are included in transformers. The text generation nodes are also very similar, and only really differ in the special tokens used by the prompts for the two model types.

**Comment by Iory1998** [comment]
> I'm able to load that unsloth 4bit model, but the results I'm getting with it seem pretty bad, mostly highly repetitive responses. I think it's just because this is the base model, though. You'd want to use the instruction tuned one.
> 
> Technically these are VLMs with a vision encoder as well as an LLM part, but I do think it would make sense to keep them in the same folder. I'm also thinking it might make sense to merge the two model loader nodes, since they're nearly identical and could automatically determine the model type. This would also make it compatible with other model types, in theory, as long as they are included in transformers. The text generation nodes are also very similar, and only really differ in the special tokens used by the prompts for the two model types.

I love this idea of merging the models. I played with your Pixtral quants. I have a few comment and requested features. 
- I think the quant is good and efficient (taking about 9GB of VRAM max), but I feel like I'd want a higher quant level. Could you make an FP8?
- Please, add a System prompt space in the node. Pixtral might not need it, but the Llama-3.2 does have one. System prompt are essential to steer the model to output in a certain way. I would love to input both the System and User prompts.
- Could you let the model read the chat template automatically? Or at least create a node where the suer can paste it.
- For the specific Vision tags, why don't you use the approach as the Florence2 node does? The user chooses between Caption, Detailed Caption, More Detailed Caption, Region, etc. 
- As for the Model folder, just make it the models/LLM folder.
For now, these are my comments.

Thank you very much.

**Comment by SeanScripts** [comment]
> I think the quant is good and efficient (taking about 9GB of VRAM max), but I feel like I'd want a higher quant level. Could you make an FP8?

This one works as an 8-bit version of Pixtral 12B, though I wish they would add some info to the model card: https://huggingface.co/DewEfresh/pixtral-12b-8bit

It works, but it's pretty slow (2.3 tok/s on a 4090). I think it's int8 rather than fp8. I could probably make an fp8 version.

> Please, add a System prompt space in the node. Pixtral might not need it, but the Llama-3.2 does have one. System prompt are essential to steer the model to output in a certain way. I would love to input both the System and User prompts.

Currently the prompt accepts all special tokens, so you can add the system prompt if you use the chat template directly. It's running in completion mode rather than chat mode unless you use the special tokens for chat. For example, you can add a system prompt in Llama 3.2 Vision Instruct like this:
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

(add system prompt here)<|eot_id|><|start_header_id|>user<|end_header_id|>

(add user message here)<|eot_id|><|start_header_id|>assistant<|end_header_id|>


```
Then the completion generated by the model will be the assistant message, stopping at `max_new_tokens` or `<|eot_od|>`. I could go ahead and update the default to something like that. But on that note...

> Could you let the model read the chat template automatically? Or at least create a node where the user can paste it.

I do want to add some nodes for creating prompts with the correct chat template rather than entering the special tokens manually like this. I'll try to add that soon. I also think it would be nice to concatenate the messages in a way that you can continue a conversation over multiple ComfyUI executions. That might take a bit more work.

> For the specific Vision tags, why don't you use the approach as the Florence2 node does? The user chooses between Caption, Detailed Caption, More Detailed Caption, Region, etc.

Florence2 has specific tasks like this but the inputs available for them are more limited. Like you can't give Florence2 instructions on how to caption, it just has a specific <CAPTION> instruction token that cannot take any additional input, along with other specific task tokens like this. Which is why you get errors like this: `"Text input (prompt) is only supported for 'referring_expression_segmentation', 'caption_to_phrase_grounding', and 'docvqa'"`

These models don't have these specific tasks (or special tokens for these tasks, unless someone finetunes on the reserved special tokens) like that, just open-ended instruction and chat capability, which can do some similar tasks anyway as an emergent trained behavior. So you can ask for a caption but also include specific instructions on how to caption, like how detailed you want it to be, what kind of language you want to use, specific contextual information you want to include, etc.

The region thing I was messing with was a hacky attempt to do object detection with these models, but it's not really what the model was built for.

> As for the Model folder, just make it the models/LLM folder.

Yeah, I think I would like to do that. Not sure what the standard is on custom nodes adding new model folders. Like I don't know how they would sync with the shared model folder in Stability Matrix if the code is searching inside the ComfyUI model folder specifically.

**Comment by Iory1998** [comment]
Thank you for your quick reply Sean?
I feel like this custom node has more potential that meets the eye. I highly encourage you to keep on developing it. 

> I do want to add some nodes for creating prompts with the correct chat template rather than entering the special tokens manually like this. I'll try to add that soon. I also think it would be nice to concatenate the messages in a way that you can continue a conversation over multiple ComfyUI executions. That might take a bit more work.

That would be nice and very helpful. There is a custom node (that didn't work for me, I am not sure why) called LLM Party. It has some good features (on paper) that you may get some inspiration for. What I want to achieve is chaining models in a kind of a Mixture of Agents. Florence can caption an image, I then feed the output to Llama-3.2-vision to compare and append that description based on a certain guideline. Florence-2 is a good model but sometimes it might get thing wrong. 

For instance, I fed it a series of picture of the same person to caption. The person's eyes are brown, but because of the different lighting setups, Florence captions the eye color to be blue or green. This messes up the consistency. I want to train LoRA SD and Flux models. My thinking is I write in the system prompt a person's main characteristics what should remain consistent across pictures.

> It works, but it's pretty slow (2.3 tok/s on a 4090). I think it's int8 rather than fp8. I could probably make an fp8 version.

Please do so.

> Not sure what the standard is on custom nodes adding new model folders. Like I don't know how they would sync with the shared model folder in Stability Matrix if the code is searching inside the ComfyUI model folder specifically.
I think you should just assume that the majority of people are using ComfyUI portable. Many LLM custom nodes rely of a Folder named "models\LLM".
Personally, I have one model folder that I hardlink folders using a windows app called "Link Shell". So, I using one folder for all Generative AI apps.

![image](https://github.com/user-attachments/assets/6d990cd9-0df8-4c67-9aa9-5000c4661212)
